export const STEAM_LOGIN = 'auth/STEAM_LOGIN';
export const STEAM_LOGIN_COMPLETED = 'auth/STEAM_LOGIN_COMPLETED';
export const STEAM_LOGIN_FAILED = 'auth/STEAM_LOGIN_FAILED';

export const STEAM_LOGOUT = 'auth/STEAM_LOGOUT';
export const STEAM_LOGOUT_COMPLETED = 'auth/STEAM_LOGOUT_COMPLETED';
export const STEAM_LOGOUT_FAILED = 'auth/STEAM_LOGOUT_FAILED';

export const SET_USER = 'auth/STEAM_USER';
export const SET_USER_COMPLETED = 'auth/SET_USER_COMPLETED';
export const SET_USER_FAILED = 'auth/SET_USER_FAILED';